name: Level 1 - Yoshi's Island

on:
  workflow_dispatch: {}
  # disable, otherwise it runs for EVERY push to main
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build
        run: ./gradlew build